version: '3'

services:

  django_app:
    build: .
    volumes:
      - .:/home/appuser/personal_site
      - static_volume:/home/appuser/personal_site/personal_site/static  # <-- bind the static volume
      - media_volume:/home/appuser/personal_site/media  # <-- bind the media volume
    networks:
      - nginx_network
    restart: always

  nginx:
    image: nginx:1.15-alpine
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/home/appuser/personal_site/personal_site/static  # <-- bind the static volume
      - media_volume:/home/appuser/personal_site/media  # <-- bind the media volume
    labels:
      - "traefik.enabled=true"
      - "traefik.backend=personal_site"
      - "traefik.frontend.rule=Host:ashford.sh"
      - "traefik.docker.network=traefik_default"
      - "traefik.port=8000"
    depends_on:  # <-- wait for django_app to be "ready" before starting this service
      - django_app
    restart: always
    networks:
      - nginx_network
      - traefik_default

networks:
  nginx_network:
    driver: bridge
  traefik_default:
    external:
      name: traefik_default

volumes:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume
