# Generated by Django 2.1.7 on 2019-03-15 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('blog', '0005_blogtagindexpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailimages.image',),
        ),
        migrations.RemoveField(
            model_name='blogpagegalleryimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogpagegalleryimage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='intro',
        ),
        migrations.DeleteModel(
            name='BlogPageGalleryImage',
        ),
        migrations.AddField(
            model_name='displayimage',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogPage'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='display_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.DisplayImage'),
        ),
    ]
