# Generated by Django 2.1.7 on 2019-03-15 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('blog', '0006_auto_20190315_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displayimage',
            name='image_ptr',
        ),
        migrations.RemoveField(
            model_name='displayimage',
            name='post',
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='display_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
        migrations.DeleteModel(
            name='DisplayImage',
        ),
    ]
